import { describe, expect, it } from "vitest";
import { parseLibreViewCsv } from "./libre-csv";

const CSV_PT = `Dados de glicose,Gerado em,12-07-2026 10:00 UTC,Gerado por,Rivaldo
Dispositivo,Número de série,Carimbo de data/hora do dispositivo,Tipo de registro,Histórico de glicose mg/dL,Leitura de glicose mg/dL
FreeStyle Libre 2,ABC123,10-07-2026 08:00,0,142,
FreeStyle Libre 2,ABC123,10-07-2026 08:15,0,150,
FreeStyle Libre 2,ABC123,10-07-2026 08:20,1,,164
FreeStyle Libre 2,ABC123,10-07-2026 08:30,6,,
FreeStyle Libre 2,ABC123,10-07-2026 08:45,0,,`;

const CSV_EN = `Glucose Data,Generated on,07-12-2026 10:00 UTC,Generated by,Rivaldo
Device,Serial Number,Device Timestamp,Record Type,Historic Glucose mg/dL,Scan Glucose mg/dL
FreeStyle Libre 2,ABC123,07-10-2026 08:00 AM,0,142,
FreeStyle Libre 2,ABC123,07-10-2026 01:15 PM,1,,180`;

describe("parseLibreViewCsv", () => {
  it("lê o export em português (tipos 0 e 1, DD-MM-YYYY)", () => {
    const { readings, skipped } = parseLibreViewCsv(CSV_PT);
    expect(readings).toHaveLength(3);
    expect(readings[0].valueMgDl).toBe(142);
    expect(readings[0].source).toBe("libre");
    expect(readings[0].recordedAt).toContain("2026-07-10");
    expect(readings[2].valueMgDl).toBe(164);
    expect(skipped).toBe(1); // linha tipo 0 sem valor
  });

  it("lê o export em inglês (AM/PM, MM-DD-YYYY)", () => {
    const { readings } = parseLibreViewCsv(CSV_EN);
    expect(readings).toHaveLength(2);
    expect(readings[1].valueMgDl).toBe(180);
    const hour = new Date(readings[1].recordedAt).getHours();
    expect(hour).toBe(13);
  });

  it("gera externalId estável para dedup em reimportações", () => {
    const a = parseLibreViewCsv(CSV_PT).readings[0].externalId;
    const b = parseLibreViewCsv(CSV_PT).readings[0].externalId;
    expect(a).toBe(b);
    expect(a).toMatch(/^libre:/);
  });

  it("arquivo sem cabeçalho conhecido devolve vazio", () => {
    expect(parseLibreViewCsv("a,b,c\n1,2,3").readings).toHaveLength(0);
  });
});
