-- Ordem estável das mensagens do copiloto.
--
-- A persistência gravava pergunta e resposta num INSERT único, e no Postgres
-- `now()` é o instante da TRANSAÇÃO: as duas linhas saíam com `created_at`
-- idêntico ao microssegundo. Com o empate, `order by created_at` devolve ordem
-- arbitrária, e a conversa restaurada aparecia com a resposta antes da pergunta.
--
-- Não era intermitente: toda conversa reaberta tinha o mesmo empate, porque a
-- causa é a semântica de `now()`, não corrida de relógio.
--
-- Duas saídas foram consideradas. Deslocar o timestamp da resposta em alguns
-- milissegundos resolveria a exibição, mas gravaria uma hora que não aconteceu
-- para fazer a ordenação funcionar — dado torto a serviço de apresentação. A
-- coluna de sequência ordena sem mentir sobre quando a mensagem existiu, e não
-- depende de relógio nenhum.

alter table public.ai_messages
  add column if not exists seq bigint generated by default as identity;

comment on column public.ai_messages.seq is
  'Ordem de inserção. É por ela que a conversa é lida, não por created_at: pergunta e resposta são gravadas na mesma transação e compartilham o mesmo now(), então created_at empata e não desempata.';

-- Ordem de leitura real: por thread, e dentro do mesmo instante a pergunta vem
-- antes da resposta.
create index if not exists ai_messages_thread_seq_idx
  on public.ai_messages (thread_id, seq);

-- Corrige as linhas que já existem: a identidade foi atribuída na reescrita da
-- tabela, em ordem que ninguém garante. Reatribui por (created_at, papel), com
-- 'user' antes de 'assistant' no empate — que é a única ordem possível, já que
-- a resposta não existe antes da pergunta.
with ordenadas as (
  select id, row_number() over (
    order by created_at, case when role = 'user' then 0 else 1 end
  ) as nova_seq
  from public.ai_messages
)
update public.ai_messages m
set seq = o.nova_seq
from ordenadas o
where m.id = o.id;

-- Evita colisão entre a sequência e as linhas recém-renumeradas.
select setval(
  pg_get_serial_sequence('public.ai_messages', 'seq'),
  coalesce((select max(seq) from public.ai_messages), 0) + 1,
  false
);

-- Rollback:
--   drop index if exists public.ai_messages_thread_seq_idx;
--   alter table public.ai_messages drop column if exists seq;
